!*==/home/marcusmae/nasa/nastran/SPAGged/C_MA1XX.f90  created by SPAG 8.01RF at 14:46 on  2 Dec 2023
MODULE C_MA1XX
   USE ISO_FORTRAN_ENV
   REAL(REAL64), DIMENSION(9) :: B
   REAL(REAL64), DIMENSION(18) :: D
   REAL(REAL64), DIMENSION(1) :: Dz
   REAL(REAL64), DIMENSION(3) :: Fl, M, R
END MODULE C_MA1XX
