!*==/home/marcusmae/nasa/nastran/SPAGged/C_EMGTRX.f90  created by SPAG 8.01RF at 14:47 on  2 Dec 2023
MODULE C_EMGTRX
   USE ISO_FORTRAN_ENV
   REAL(REAL64), DIMENSION(225) :: A
   REAL(REAL64) :: Bfact, Sxubc, Xsubb, Ysubc
   REAL(REAL64), DIMENSION(18) :: E
   REAL(REAL64), DIMENSION(324) :: Kk, Kout
   REAL(REAL64), DIMENSION(81) :: Ksav
   REAL(REAL64), DIMENSION(9) :: Prod, Temp9
END MODULE C_EMGTRX
