!*==/home/marcusmae/nasa/nastran/SPAGged/C_SMA1DP.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_SMA1DP
   IMPLICIT NONE
!SMA1BD
!
!
!     SMA1 VARIABLE CORE BOOKKEEPING PARAMETERS
!
!
!     SMA1 PROGRAM CONTROL PARAMETERS
!
!
!     ECPT COMMON BLOCK
!
   REAL*8, DIMENSION(514) :: Dpdum
END MODULE C_SMA1DP
