!*==/home/marcusmae/nasa/nastran/SPAGged/C_MSGX.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_MSGX
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(4, 40) :: Msg
   INTEGER :: Msglg, Nmsg
!
!     -------------------     / MSGX   /     ---------------------------
!
!     MSGX DEFINES A TABLE WHERE MESSAGES ARE QUEUED.
!     NMSG   = NUMBER OF MESSAGES CURRENTLY IN QUEUE.
!     MSGLG  = TOTAL NO. OF ENTRIES IN THE MESSAGE QUEUE.
!     MSG    = TABLE OF FOUR-WORD ENTRIES WHERE MESSAGES ARE STORED.
!
   DATA nmsg/0/ , msglg/40/ , msg/160*0/

END MODULE C_MSGX
