!*==/home/marcusmae/nasa/nastran/SPAGged/C_NUMTPX.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_NUMTPX
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(19) :: Bcd
   INTEGER :: Nbcd
!
!     -------------------     /NUMTPX /     ----------------------------
!
!     BCD-LOOK ALIKE FLOATING NUMBERS, USED ONLY BY NUMTYP SUBROUTINE.
!     DATA WILL BE LOADED FROM NASINFO.DOC FILE BY NSINFO
!
   DATA nbcd/0/
   DATA bcd/19*0/

END MODULE C_NUMTPX
