!*==/home/marcusmae/nasa/nastran/SPAGged/C_OUTPUT.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_OUTPUT
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(224) :: Output
!
!     -------------------     / OUTPUT /     ---------------------------
!
!     OUTPUT DEFINES A STORAGE BLOCK WHERE PROBLEM TITLE, SUBTITLE
!     AND LABEL ARE STORED.
!
   DATA output/224*4H    /
!
END MODULE C_OUTPUT
