!*==/home/marcusmae/nasa/nastran/SPAGged/C_XVPS.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XVPS
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(600) :: Vps
!
!     -------------------     / XVPS   /     ---------------------------
!
!     XVPS IS THE VARIABLE PARAMETER STORAGE TABLE.
!     VPS(1) = TOTAL NO. OF WORDS IN VPS.
!     VPS(2) = POINTER TO LAST WORD USED IN VPS.
!     VPS(3) = TABLE FOR STORAGE OF PARAMETERS
!              (VARIABLE NO OF WORDS/ENTRY).
!
   DATA vps/600 , 2 , 598*0/

END MODULE C_XVPS
