!*==/home/marcusmae/nasa/nastran/SPAGged/C_XXREAD.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XXREAD
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER :: Inflag, Insave
   INTEGER, DIMENSION(3) :: Ixxr
!
!     --------------------    / XXREAD /     ---------------------------
!
!     INFLAG AND INSAVE ARE USED IN READFILE COMMAND. IRRX USED IN
!     FFREAD
!
   DATA inflag , insave , ixxr/5*0/
!

END MODULE C_XXREAD
