!*==tmtsot.f90  processed by SPAG 7.61RG at 01:00 on 21 Mar 2022
 
SUBROUTINE tmtsot
   IMPLICIT NONE
   USE c_ntime
   USE c_system
!
!     THIS SUBROUTINE PRINTS THE CONTENTS OF COMMON /NTIME/
!
!
   WRITE (nout,99001) nitems
99001 FORMAT (1H1,23X,' DIAG 35 OUTPUT OF TIMING CONSTANTS IN COMMON /NTIME/'/24X,                                                  &
             &' ----------------------------------------------------'//' NUMBER OF TIMING CONSTANTS IN COMMON /NTIME/   ',          &
             &'                         --- ',I11/)
   WRITE (nout,99002) tgino
99002 FORMAT (' READ + WRITE + BACKWARD READ                   ',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99003) tbldpk
99003 FORMAT (' BLDPK  - PACK   SUCCESSIVE ELEMENTS OF A COLUMN',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99004) tintpk
99004 FORMAT (' INTPK  - UNPACK SUCCESSIVE ELEMENTS OF A COLUMN',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99005) tpack
99005 FORMAT (' PACK   - PACK   AN ENTIRE COLUMN               ',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99006) tunpak
99006 FORMAT (' UNPACK - UNPACK AN ENTIRE COLUMN               ',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99007) tgetst
99007 FORMAT (' GETSTR - FORWARD READ  A STRING OF DATA        ',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99008) tputst
99008 FORMAT (' PUTSTR - WRITE A STRING OF DATA                ',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99009) ttlrsp
99009 FORMAT (' TIGHT-LOOP MULTIPLY - REAL    SINGLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99010) ttlrdp
99010 FORMAT (' TIGHT-LOOP MULTIPLY - REAL    DOUBLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99011) ttlcsp
99011 FORMAT (' TIGHT-LOOP MULTIPLY - COMPLEX SINGLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99012) ttlcdp
99012 FORMAT (' TIGHT-LOOP MULTIPLY - COMPLEX DOUBLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99013) tllrsp
99013 FORMAT (' LOOSE-LOOP MULTIPLY - REAL    SINGLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99014) tllrdp
99014 FORMAT (' LOOSE-LOOP MULTIPLY - REAL    DOUBLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99015) tllcsp
99015 FORMAT (' LOOSE-LOOP MULTIPLY - COMPLEX SINGLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99016) tllcdp
99016 FORMAT (' LOOSE-LOOP MULTIPLY - COMPLEX DOUBLE PRECISION ',' (AVERAGE PER OPERATION) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99017) tgetsb
99017 FORMAT (' GETSTB - BACKWARD READ  A STRING OF DATA       ',' (AVERAGE PER WORD     ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99018) rgino
99018 FORMAT (' READ + WRITE + BACKWARD READ                   ',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99019) rbldpk
99019 FORMAT (' BLDPK  - PACK   SUCCESSIVE ELEMENTS OF A COLUMN',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99020) rintpk
99020 FORMAT (' INTPK    UNPACK SUCCESSIVE ELEMENTS OF A COLUMN',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99021) rpack
99021 FORMAT (' PACK   - PACK   AN ENTIRE COLUMN               ',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99022) runpak
99022 FORMAT (' UNPACK - UNPACK AN ENTIRE COLUMN               ',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99023) rgetst
99023 FORMAT (' GETSTR - READ  A STRING OF DATA                ',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   WRITE (nout,99024) rputst
99024 FORMAT (' PUTSTR - WRITE A STRING OF DATA                ',' (AVERAGE PER RECORD   ) --- ',E11.4,' MICROSECONDS'/)
   IF ( isy77/=-3 ) WRITE (nout,99025)
99025 FORMAT ('0*** NASTRAN INFORMATION MESSAGE, TO INCORPORATE THESE ','TIMING CONSTANTS INTO NASTRAN PERMANENTLY',/5X,            &
             &'RE-RUN JOB WITH ''NASTRAN BULKDATA=-3'' FOR MORE ','INSTRUCTIONS',/)
END SUBROUTINE tmtsot
