!*==cmckdf.f90 processed by SPAG 8.01RF 16:19  2 Dec 2023
!!SPAG Open source Personal, Educational or Academic User  NON-COMMERCIAL USE - Not for use on proprietary or closed source code
!!SPAG Open source Personal, Educational or Academic User  NON-COMMERCIAL USE - Not for use on proprietary or closed source code
 
SUBROUTINE cmckdf
   USE c_blank
   USE c_cmb001
   USE c_cmb002
   USE c_cmb003
   USE c_xmssg
   USE c_zzzzzz
   IMPLICIT NONE
!
! Local variable declarations rewritten by SPAG
!
   INTEGER , DIMENSION(9) :: ce
   REAL , DIMENSION(7,9) :: cstm
   INTEGER , DIMENSION(7) :: cstmid , idpsub , ist
   REAL , DIMENSION(4) :: ecpt
   INTEGER :: ecpt1 , i , ibgss , icstm , ifile , imsg , isub , isum , j , jj , k , kk , llco , loc , ncsub , nn , npt , nptm1 , nw
   LOGICAL :: ferror , first
   INTEGER , DIMENSION(1) :: iz
   INTEGER , DIMENSION(2) , SAVE :: nam
   REAL , DIMENSION(9) :: tt
   EXTERNAL close , fwdrec , mesage , open , pretrs , read , skpfil , transs
!
! End of declarations rewritten by SPAG
!
   INTEGER :: spag_nextblock_1
   INTEGER :: spag_nextblock_2
!
!     THIS SUBROUTINE DETERMINES WHETHER ALL (TRANSFORMED) LOCAL
!     COORDINATE SYSTEMS SPECIFIED AT A GIVEN CONNECTION ARE COMPATABLE
!
   !>>>>EQUIVALENCE (Iz(1),Z(1)) , (ecpt1,ecpt(1))
   DATA nam/4HCMCK , 4HDF  /
   spag_nextblock_1 = 1
   SPAG_DispatchLoop_1: DO
      SELECT CASE (spag_nextblock_1)
      CASE (1)
!
         DO i = 2 , 4
            ecpt(i) = 0.0
         ENDDO
         ferror = .TRUE.
!
!     READ CSTM INTO OPEN CORE
!
         ifile = sccstm
         icstm = score
         llco = lcore
         CALL open(*80,sccstm,z(buf2),0)
         CALL read(*20,*20,sccstm,z(icstm),llco,1,nw)
         spag_nextblock_1 = 2
         CYCLE SPAG_DispatchLoop_1
 20      llco = llco - nw
         CALL close(sccstm,1)
         IF ( nw==0 ) RETURN
         CALL pretrs(z(icstm),nw)
!
!     READ ALL BGSS FILES INTO OPEN CORE
!
         ibgss = score + nw
         ifile = scsfil
         CALL open(*80,scsfil,z(buf2),0)
         jj = 0
         DO i = 1 , npsub
            ist(i) = ibgss + jj
            ncsub = combo(i,5) + 1
            DO j = 1 , ncsub
               CALL fwdrec(*100,scsfil)
            ENDDO
            CALL read(*80,*30,scsfil,z(ibgss+jj),llco,1,nn)
            spag_nextblock_1 = 2
            CYCLE SPAG_DispatchLoop_1
 30         llco = llco - nn
            jj = jj + nn + 1
            CALL skpfil(scsfil,1)
         ENDDO
         CALL close(scsfil,1)
!
!     BEGIN READING CONNECTION ENTRIES
!
         ifile = scconn
         CALL open(*80,scconn,z(buf2),0)
         CALL read(*60,*40,scconn,ce,10,1,nn)
         spag_nextblock_1 = 2
         CYCLE SPAG_DispatchLoop_1
 40      npt = 0
         DO i = 1 , npsub
!
!     CE(3)...CE(NN) ARE INTERNAL POINT NO.
!
            IF ( ce(i+2)/=0 ) THEN
               npt = npt + 1
               loc = ist(i) + (ce(i+2)-1)*4
               cstmid(npt) = iz(loc)
               idpsub(npt) = i
            ENDIF
         ENDDO
!
!     CHECK FOR NO CSTMS THIS ENTRY
!
         isum = 0
         DO i = 1 , npt
            isum = isum + cstmid(i)
         ENDDO
         IF ( isum/=0 ) THEN
!
!     GET CSTM MATRICES AND LOAD INTO CSTM ARRAY
!
            DO i = 1 , npt
               ecpt1 = cstmid(i)
               IF ( ecpt1==0 ) THEN
                  DO j = 1 , 9
                     cstm(i,j) = 0.0
                  ENDDO
                  cstm(i,1) = 1.0
                  cstm(i,5) = 1.0
                  cstm(i,9) = 1.0
               ELSE
                  CALL transs(ecpt,tt)
                  DO j = 1 , 9
                     cstm(i,j) = tt(j)
                  ENDDO
               ENDIF
            ENDDO
!
!     COMPARE EACH MATRIX AGAINST OTHERS
!
            nptm1 = npt - 1
            DO i = 1 , nptm1
               first = .TRUE.
               j = i + 1
               DO k = j , npt
                  spag_nextblock_2 = 1
                  SPAG_DispatchLoop_2: DO
                     SELECT CASE (spag_nextblock_2)
                     CASE (1)
                        SPAG_Loop_5_1: DO kk = 1 , 9
                           IF ( abs(cstm(i,kk)-cstm(k,kk))>=1.E-3 ) THEN
                              spag_nextblock_2 = 2
                              EXIT SPAG_Loop_5_1
                           ENDIF
                        ENDDO SPAG_Loop_5_1
                     CASE (2)
                        IF ( ferror ) THEN
                           ferror = .FALSE.
                           WRITE (outt,99001) ufm
!    2        ', SUMMARY FOLLOWS.', /5X,'(LOCAL COORDINATE SYSTEMS ARE',
!    3        ' THE TRNASFORMED OVERALL STSTEM GENERATED BY COMB1,',
!    4        /5X,'SEE PROGRM. MANUAL P 4.128-7, 9TH STEP)', //,
!    5        ' *** SUGGESTION - YOUR SUBSTRUCTURING PROBLEM MAY ',
!    6        'REQUIRE THE ''GTRAN'' CARD(S) ***',/)
!
99001                      FORMAT (A23,' 6528, INCOMPATABLE LOCAL COORDINATE SYSTEMS HAVE ','BEEN FOUND.',/5X,                      &
                                  &'CONNECTION OF POINTS IS IMPOSSIBLE','. (SUGGESTION - USE ''GTRAN'' CARD(S))',/5X,               &
                                  &'SUMMARY IN TERMS OF THE JUST-FORMED INTERNAL DOF AND ','INTERNAL COORD. SYSTEM ID''S PER',/5X,  &
                                  &'THE EQSS AND BGSS FOLLOWS.',/)
                        ENDIF
                        IF ( first ) THEN
                           first = .FALSE.
                           isub = idpsub(i) + 2
                           WRITE (outt,99002) cstmid(i) , cstm(i,1) , cstm(i,4) , cstm(i,7) , idpsub(i) , cstm(i,2) , cstm(i,5) ,   &
                                & cstm(i,8) , ce(isub) , cstm(i,3) , cstm(i,6) , cstm(i,9)
99002                      FORMAT (/1X,76(1H*),/,' THE FOLLOWING MISMATCHED LOCAL COORDINATE',' SYSTEMS (CSTM) HAVE BEEN FOUND FOR',&
                                 & //,' LOCAL COORDINATE SYSTEM ID NO.',I9,8X,3E9.2,/,' PSEUDOSTRUCTURE ID NO.',I5,20X,3E9.2,/,     &
                                  &' INTERNAL POINT NO.',I9,20X,3E9.2)
                           idry = -2
                        ENDIF
                        isub = idpsub(k) + 2
                        WRITE (outt,99003) cstmid(k) , cstm(k,1) , cstm(k,4) , cstm(k,7) , idpsub(k) , cstm(k,2) , cstm(k,5) ,      &
                             & cstm(k,8) , ce(isub) , cstm(k,3) , cstm(k,6) , cstm(k,9)
99003                   FORMAT (/12X,'AND',7X,'LOCAL COORDINATE SYSTEM ID NO.',I9,8X,3E9.2,/22X,'PSEUDOSTRUCTURE ID NO.',I5,20X,    &
                              & 3E9.2,/22X,'INTERNAL POINT NO.',I9,20X,3E9.2)
                        EXIT SPAG_DispatchLoop_2
                     END SELECT
                  ENDDO SPAG_DispatchLoop_2
               ENDDO
            ENDDO
         ENDIF
         CALL read(*60,*40,scconn,ce,10,1,nn)
         spag_nextblock_1 = 2
         CYCLE SPAG_DispatchLoop_1
!
 60      CALL close(scconn,1)
         RETURN
!
 80      imsg = -1
         spag_nextblock_1 = 3
         CYCLE SPAG_DispatchLoop_1
 100     imsg = -2
         spag_nextblock_1 = 3
      CASE (2)
         imsg = -8
         spag_nextblock_1 = 3
      CASE (3)
         CALL mesage(imsg,ifile,nam)
         EXIT SPAG_DispatchLoop_1
      END SELECT
   ENDDO SPAG_DispatchLoop_1
!
END SUBROUTINE cmckdf
