!*==ifp1d.f90 processed by SPAG 8.01RF 16:20  2 Dec 2023
!!SPAG Open source Personal, Educational or Academic User  NON-COMMERCIAL USE - Not for use on proprietary or closed source code
!!SPAG Open source Personal, Educational or Academic User  NON-COMMERCIAL USE - Not for use on proprietary or closed source code
 
SUBROUTINE ifp1d(Msno)
   USE c_system
   USE c_xmssg
   IMPLICIT NONE
!
! Dummy argument declarations rewritten by SPAG
!
   INTEGER :: Msno
!
! Local variable declarations rewritten by SPAG
!
   INTEGER :: amsno , iwher
   INTEGER , SAVE :: maxmsg
   EXTERNAL page , page1
!
! End of declarations rewritten by SPAG
!
!
!     MESSAGE WRITER FOR IFP1
!
   DATA maxmsg/646/
!
   amsno = iabs(Msno)
   IF ( Msno<0 ) nogo = 1
   IF ( amsno<=maxmsg ) THEN
      IF ( amsno==612 ) CALL page1
      IF ( Msno<=0 ) WRITE (nout,99001) ufm , amsno
99001 FORMAT (A23,I7)
      IF ( Msno>0 ) WRITE (nout,99002) uwm , amsno
99002 FORMAT (A25,I5)
      IF ( amsno>=634 .AND. amsno<=644 ) WRITE (nout,99003)
99003 FORMAT (1H+,37X,'(FROM SCAN)')
      iwher = amsno - 600
      IF ( iwher==1 ) THEN
!
         WRITE (nout,99004)
99004    FORMAT (' THE KEYWORD ON THE ABOVE CARD TYPE IS ILLEGAL OR MISS','PELLED.  SEE THE FOLLOWING LIST FOR LEGAL KEYWORDS.')
      ELSEIF ( iwher==2 ) THEN
         WRITE (nout,99005)
99005    FORMAT (' TWO OR MORE OF THE ABOVE CARD TYPES DETECTED WHERE ','ONLY ONE IS LEGAL.',/,' THE LAST FOUND WILL BE USED.')
         line = line + 1
      ELSEIF ( iwher==3 ) THEN
         WRITE (nout,99006)
99006    FORMAT (' THE ABOVE CARD DOES NOT END PROPERLY. COMMENTS SHOULD','BE PRECEEDED',/,' BY A DOLLAR SIGN.')
         line = line + 1
      ELSEIF ( iwher==4 ) THEN
         WRITE (nout,99007)
99007    FORMAT (' THE ABOVE CARD HAS A NON-INTEGER IN AN INTEGER FIELD.')
      ELSEIF ( iwher==5 ) THEN
         WRITE (nout,99008)
99008    FORMAT (' A SYMSEQ OR SUBSEQ CARD APPEARS WITHOUT A SYMCOM OR ','SUBCOM CARD.')
      ELSEIF ( iwher==6 ) THEN
         WRITE (nout,99009)
99009    FORMAT (' A REQUEST FOR TEMPERATURE DEPENDENT MATERIALS OCCURS AT',' THE SUBCASE LEVEL.',/,                                &
               & ' ONLY ONE ALLOWED PER PROBLEM.')
      ELSEIF ( iwher==7 ) THEN
         WRITE (nout,99010)
99010    FORMAT (' A REPCASE CARD MUST BE PROCEEDED BY A SUBCASE CARD')
      ELSEIF ( iwher==8 ) THEN
         WRITE (nout,99011)
99011    FORMAT (' THE SET ID SPECIFIED ON THE ABOVE CARD MUST BE DEFINED',' PRIOR TO THIS CARD.')
      ELSEIF ( iwher==9 ) THEN
         WRITE (nout,99012)
99012    FORMAT (' SUBCASE DELIMITER CARDS MUST HAVE A UNIQUE IDENTIFYING',' INTEGER.')
      ELSEIF ( iwher==10 ) THEN
         WRITE (nout,99013)
99013    FORMAT (' NO SET ID SPECIFIED.  ALL WILL BE ASSUMED.')
      ELSEIF ( iwher==11 ) THEN
         WRITE (nout,99014)
99014    FORMAT (' TEN CARDS HAVE ILLEGAL KEY WORDS. NASTRAN ASSUMES BEGIN',' BULK CARD',/,' IS MISSING. IT WILL NOW PROCESS YOUR ',&
                &'BULK DATA.')
         line = line + 1
      ELSEIF ( iwher==12 ) THEN
!
!     THE LIST OF CASE CONTROL CARDS IS FORMATTED FOR SHORT PAPER
!
         WRITE (nout,99015)
99015    FORMAT (///,10(1H-),' THE FOLLOWING IS A LIST OF VALID CASE ','CONTROL KEY WORDS EXCEPT FOR THE PLOTTER PACKAGES.',10(1H-),&
               & //6X,'KEYWORD',20X,'MEANING',/)
         WRITE (nout,99016)
99016    FORMAT (5X,'ACCELERATION',12X,'OUTPUT REQUEST FOR ACCELERATION VECTORS',/6X,'AEROFORCE',15X,                               &
                &'OUTPUT REQUEST FOR AERODYNAMIC FORCES',/6X,'AXISYMMETRIC',12X,'AXISYMMETRIC CASE SELECTION (SINE OR COSINE)',/6X, &
                &'B2PP',20X,'SELECTION OF STRUCTURAL DAMPING OR THERMAL CAPACITANCE ','MATRICES',/6X,'CMETHOD',17X,                 &
                &'COMPLEX EIGENVALUE METHOD SELECTION',/6X,'DEFORM',18X,'REQUEST FOR ENFORCED ELEMENT DEFORMATION',/6X,             &
                &'DISPLACEMENT',12X,'OUTPUT REQUEST FOR DISPLACEMENT VECTORS',/6X,'DLOAD',19X,'DYNAMIC LOAD SELECTION')
         WRITE (nout,99017)
99017    FORMAT (6X,'DSCOEFFICIENT',11X,'DIFFERENTIAL STIFFNESS COEFFICIENT SET SELECTION',/6X,'ECHO',20X,                          &
                &'BULK DATA ECHO SELECTOR (SORT,UNSORT,BOTH,NONE,PUNCH)',/6X,'ELFORCE',17X,'OUTPUT REQUEST FOR ELEMENT FORCES',/6X, &
                &'ELSTRESS',16X,'OUTPUT REQUEST FOR ELEMENT STRESSES',/6X,'ESE',21X,'REQUEST FOR ELEMENT STRAIN ENERGY OUTPUT',/6X, &
                &'FMETHOD',17X,'REQUEST FOR AEROELASTIC FLUTTER METHOD',/6X,'FORCE',18X,'OUTPUT REQUEST FOR ELEMENT FORCES',/6X,    &
                &'FREQUENCY',15X,'FREQUENCY SET SELECTION')
         WRITE (nout,99018)
99018    FORMAT (6X,'GPFORCE',17X,'REQUEST FOR GRID POINT FORCE BALANCE OUTPUT',/6X,'GUST',20X,                                     &
                &'AEROELASTIC RESPONSE ANALYSIS INPUT LOADING CONDITION',/6X,'HARMONICS',15X,                                       &
                &'HARMONICS TO BE PRINTED FOR AXISYMMETRIC SHELL PROBLEM',/6X,'IC',22X,                                             &
                &'INITIAL CONDITIONS FOR DIRECT TRANSIENT PROBLEM',/6X,'K2PP',20X,                                                  &
                &'SELECTION OF STRUCT-L STIFFNESS OR THERMAL CONDUCTANCE ','MATRICES',/6X,'LABEL',19X,                              &
                &'DEFINES PRINTER, PLOTTER AND PUNCH OUTPUT LABEL',/6X,'LINE',20X,                                                  &
                &'NUMBER OF LINES PER PAGE (DFLT = 50 -CDC,IBM, 45 -UNIVAC)',/6X,'LOAD',20X,                                        &
                &'STATIC ANALYSIS EXTERNAL LOAD SELECTION OR HEAT POWER/','FLUX')
         WRITE (nout,99019)
99019    FORMAT (6X,'M2PP',20X,'SELECTION OF INPUT MASS MATRICES VIA DMIG CARDS',/6X,'MAXLINES',16X,                                &
                &'MAXIMUM NUMBER OF PRINTER LINES (DEFAULT = 20000)',/6X,'METHOD',18X,'REAL EIGENVALUE METHOD SELECTION',/6X,       &
               & 'MODES',19X,'DUPLICATE CASE CONTROL THIS MANY TIMES',/6X,'MPC',21X,                                                &
                &'SELECTS MULTI-POINT CONSTRAINTS OR HEAT TRANSFER ','BOUNDARY TEMPS',/6X,'MPCFORCE',16X,                           &
                &'OUTPUT REQUEST FOR MULTI-POINT FORCES OF CONSTRAINT',/6X,'NCHECK',18X,                                            &
                &'OUTPUT REQUEST FOR FORCE AND STRESS PRECISION',/6X,'NLLOAD',18X,                                                  &
                &'OUTPUT REQUEST FOR NON-LINEAR LOADS FOR ANALYSIS SET')
!
         CALL page1
         WRITE (nout,99020)
99020    FORMAT (//6X,7HKEYWORD,20X,7HMEANING,//6X,'NONLINEAR',15X,'NON-LINEAR LOAD SET FOR TRANSIENT PROBLEMS',/6X,'OFREQUENCY',   &
               & 14X,'SELECTS OUTPUT FREQUENCIES OR -IM- PART OF COMPLEX ','EIGENVALUES',/6X,'OLOAD',19X,                           &
                &'OUTPUT REQUEST FOR APPLIED LOAD',/6X,'OTIME',19X,'REQUEST FOR SELECTED OUTPUT TIMES',/6X,'OUTPUT',18X,            &
                &'OUTPUT PACKET DELIMITER (THIS CARD IS OPTIONAL)',/6X,'OUTPUT(PLOT)',12X,                                          &
                &'STRUCTURE PLOTTER OUTPUT PACKET DELIMITER',/6X,'OUTPUT(XYOUT)',11X,                                               &
                &'XY OUTPUT PACKET DELIMITER (PLOTTER, PRINTER AND PUNCH)',/6X,'OUTPUT(XYPLOT)',10X,'EQUIVALENT TO OUTPUT(XYOUT)')
         WRITE (nout,99021)
99021    FORMAT (6X,'PLCOEFFICIENT',11X,'PIECEWISE LINEAR COEFFICIENT SET SELECTION',/6X,'PLOTID',18X,                              &
                &'DEFINES PLOTTER OUTPUT HEADER FRAME TITLE',/6X,'PRESSURE',16X,'OUTPUT REQUEST FOR HYDROELASTIC PRESSURE',/6X,     &
                &'RANDOM',18X,'RANDOM ANALYSIS PSDL AND RANDT SET SELECTION',/6X,'REPCASE',17X,'REPEAT THE PRECEDING CASE AGAIN',   &
               & /6X,'SACCELERATION',11X,'OUTPUT REQUEST FOR SOLUTION SET ACCELERATION VECTORS',/6X,'SCAN',20X,                     &
                &'SCAN AND OUTPUT STRESSES OR FORCES FOR PREDETERMINED ','CRITERIA',/6X,'SDAMPING',16X,                             &
                &'MODAL FORMULATION STRUCTURAL DAMPING TABULAR FUNCTION ','SELECTION',/6X,'SDISPLACEMENT',11X,                      &
                &'OUTPUT REQUEST FOR SOLUTION SET DISPLACEMENT VECTORS')
         WRITE (nout,99022)
99022    FORMAT (6X,'SET',21X,'DEFINES OUTPUT SET LIST',/6X,'SPC',21X,'SELECTS SINGLE POINT CONSTRAINTS OR HEAT TRANSFER ',         &
                &'BOUNDARY TEMP',/6X,'SPCFORCE',16X,'REQUESTS SINGLE POINT CONSTRAINT FORCES OR THERMAL POWER',/6X,'STRAIN',18X,    &
                &'OUTPUT REQUEST FOR ELEMENT STRAINS',/6X,'STRESS',18X,'OUTPUT REQUEST FOR ELEMENT STRESSES',/6X,'SUBCASE',17X,     &
                &'SUBCASE DELIMITER',/6X,'SUBCOM',18X,'THIS CASE IS A LINEAR COMBINATION OF THE PRECEDING ','SUBCASES',/6X,'SUBSEQ',&
               & 18X,'DEFINES COEFFICIENTS FOR LINEAR SUBCASE COMBINATION')
         WRITE (nout,99023)
99023    FORMAT (6X,'SUBTITLE',16X,'DEFINES PRINTER, PLOTTER AND PUNCH OUTPUT SUBTITLE',/6X,'SVECTOR',17X,                          &
                &'OUTPUT REQUEST FOR SOLUTION SET DISPLACEMENT VECTORS',/6X,'SVELOCITY',15X,                                        &
                &'OUTPUT REQUEST FOR SOLUTION SET VELOCITY VECTORS',/6X,'SYM',21X,'SYMMETRY SUBCASE DELIMITER',/6X,'SYMCOM',18X,    &
                &'THIS CASE IS A LINEAR COMBINATION OF THE PRECEDING SYM ','CASES',/6X,'SYMSEQ',18X,                                &
                &'DEFINES COEFFICIENTS FOR LINEAR SYM COMBINATION (DEFAULT',' = 1.0)',/6X,'TEMPERATURE(BOTH)',7X,                   &
                &'THERMAL SET SELECTION FOR BOTH LOAD AND MATERIAL DATA',/6X,'TEMPERATURE(LOAD)',7X,                                &
                &'THERMAL LOAD TEMPERATURE SET SELECTION')
!
         CALL page1
         WRITE (nout,99024)
99024    FORMAT (//6X,'KEYWORD',20X,'MEANING',/6X,'TEMPERATURE(MATERIAL)',3X,'SELECTS THERMAL DEPENDENT MATERIALS OR TEMPERATURE ', &
                &'ESTIMATES',/6X,'TFL',21X,'TRANSFER FUNCTION SET SELECTION',/6X,'THERMAL',17X,                                     &
                &'OUTPUT REQUEST FOR TEMPERATURES IN HEAT TRANSFER ANALYSIS',/6X,'TITLE',19X,                                       &
                &'DEFINES PRINTER, PLOTTER AND PUNCH OUTPUT TITLE',/6X,'TSTEP',19X,'TIME STEP SET SELECTION FOR TRANSIENT PROBLEMS',&
               & /6X,'VECTOR',18X,'OUTPUT REQUEST FOR DISPLACEMENT VECTORS',/6X,'VELOCITY',16X,                                     &
               & 'OUTPUT REQUEST FOR VELOCITY VECTORS',/6X,'BEGIN BULK',14X,'THIS CARD MARKS THE END OF THE CASE CONTROL DECK')
         RETURN
      ELSEIF ( iwher==13 ) THEN
!
         WRITE (nout,99025)
99025    FORMAT (' THE ABOVE SET CONTAINS -EXCEPT- WHICH IS NOT PRECEDED ','BY -THRU-.')
      ELSEIF ( iwher==14 ) THEN
         WRITE (nout,99026)
99026    FORMAT (' THE ABOVE SET IS INCORRECTLY SPECIFIED.  CHECK FORMAT ','ON THIS OR PREVIOUS CARD.')
      ELSEIF ( iwher==15 ) THEN
         WRITE (nout,99027)
99027    FORMAT (' AN IMPROPER OR NO NAME GIVEN TO THE ABOVE SET.')
      ELSEIF ( iwher==16 ) THEN
         WRITE (nout,99028)
99028    FORMAT (' ELEMENT IN THRU RANGE LIES IN RANGE OF PREVIOUS THRU ','OR EXCEPT.  MISSING ELEMENT OR INCORRECT USE OF THRU.')
      ELSEIF ( iwher==17 ) THEN
         WRITE (nout,99029)
99029    FORMAT (' INCORRECT OR MISSING VALUE ON CASE CONTROL CARD. ',' CHECK FOR CORRECT CARD FORMAT.')
      ELSEIF ( iwher==18 ) THEN
         WRITE (nout,99030)
99030    FORMAT (' PLOT OUTPUT IS REQUESTED BUT THE PROPER PLOT TAPE IS ','NOT A PHYSICAL TAPE')
      ELSEIF ( iwher==22 ) THEN
!
         WRITE (nout,99031)
99031    FORMAT (' REAL VALUES NOT ALLOWED IN A THRU SEQUENCE.')
      ELSEIF ( iwher==23 ) THEN
         WRITE (nout,99032)
99032    FORMAT (' UNEXPECTED END-OF-RECORD ON CASE CONTROL CARD.  CHECK ','FOR CORRECT CARD FORMAT.')
      ELSEIF ( iwher==24 ) THEN
         WRITE (nout,99033)
99033    FORMAT (' BEGIN BULK CARD NOT FOUND.')
      ELSEIF ( iwher==25 ) THEN
         WRITE (nout,99034)
99034    FORMAT (' TOO LARGE ID ON PRECEDING SUBCASE TYPE CARD. ALL ID-S ','MUST BE LESS THAN 99,999,999.')
      ELSEIF ( iwher==26 ) THEN
         WRITE (nout,99035)
99035    FORMAT (' VALUES IN EXCEPT MUST BE SPECIFIED IN ASCENDING ORDER')
      ELSEIF ( iwher==27 ) THEN
         WRITE (nout,99036)
99036    FORMAT (' THE ABOVE SUBCASE HAS BOTH A STATIC LOAD AND A REAL ','EIGENVALUE METHOD SELECTION - REMOVE ONE.')
      ELSEIF ( iwher==28 ) THEN
         WRITE (nout,99037)
99037    FORMAT (/,' THERMAL, DEFORMATION, AND EXTERNAL LOADS CANNOT HAVE',' THE SAME SET IDENTIFICATION NUMBER.')
      ELSEIF ( iwher==29 ) THEN
         WRITE (nout,99038)
99038    FORMAT (' ECHO CARD HAS REPEATED OR UNRECOGNIZABLE SPECIFICATION',' DATA - ',/11X,'REPEATED SPECIFICATIONS WILL BE IGNORED'&
               & ,/11X,'UNRECOGNIZABLE SPECIFICATIONS WILL BE TREATED AS ','SORT.')
         line = line + 2
      ELSEIF ( iwher==30 ) THEN
         WRITE (nout,99039)
99039    FORMAT (' ECHO CARD WITH -NONE- SPECIFICATION HAS ADDITIONAL ','SPECIFICATIONS WHICH WILL BE IGNORED.')
      ELSEIF ( iwher==31 ) THEN
         WRITE (nout,99040)
99040    FORMAT (' PLOT AND/OR SET COMMAND CARD MISSING FROM STRUCTURE ','PLOTTER OUTPUT PACKAGE.')
      ELSEIF ( iwher==32 ) THEN
         WRITE (nout,99041)
99041    FORMAT (' XYPLOT COMMAND CARDS FOUND IN STRUCTURE PLOTTER OUTPUT',' PACKAGE.')
      ELSEIF ( iwher==33 ) THEN
         WRITE (nout,99042)
99042    FORMAT (' SUBCASE LIMIT OF 360 EXCEEDED')
      ELSEIF ( iwher==34 ) THEN
!
!     MESSAGES 634 - 644 (760 THRU 960) ARE CALLED ONLY BY SCAN
!
         WRITE (nout,99043)
99043    FORMAT (5X,'KEYWORD INSIDE BRACKETS IS ILLEGAL OR MIS-SPELLED')
      ELSEIF ( iwher==35 ) THEN
         WRITE (nout,99044)
99044    FORMAT (5X,'ONLY ONE SET-ID ALLOWED')
      ELSEIF ( iwher==36 ) THEN
         WRITE (nout,99045)
99045    FORMAT (5X,'EXTRA VALUE ENCOUNTERED OR WRONG TYPE OF INPUT DATA')
      ELSEIF ( iwher==37 ) THEN
         WRITE (nout,99046)
99046    FORMAT (5X,'ILLEGAL COMPONENT SPECIFIED')
      ELSEIF ( iwher==38 ) THEN
         WRITE (nout,99047)
99047    FORMAT (5X,'COMPONENT LIMIT OF 31 IS EXCEEDED')
      ELSEIF ( iwher==39 ) THEN
         WRITE (nout,99048)
99048    FORMAT (5X,'SET ID ERROR (REQUESTED BEFORE EQUAL SIGN OR ','SPLITTED ID)')
      ELSEIF ( iwher==40 ) THEN
         WRITE (nout,99049)
99049    FORMAT (5X,'TOO MANY COMPONENTS')
      ELSEIF ( iwher==41 ) THEN
         WRITE (nout,99050)
99050    FORMAT (5X,'MINUS MAX EXCEEDS PLUS MAX')
      ELSEIF ( iwher==42 ) THEN
         WRITE (nout,99051)
99051    FORMAT (5X,'COMPONENT NAME NOT AVAILABLE FOR ELEMENT SELECTED')
      ELSEIF ( iwher==43 ) THEN
         WRITE (nout,99052)
99052    FORMAT (5X,'OUTPUT SCAN BY FORCE OR BY STRESS ONLY')
      ELSEIF ( iwher==44 ) THEN
         WRITE (nout,99053)
99053    FORMAT (5X,'LARGE TOPN VALUE REQUESTED MAY RESULT IN INSUFFICIENT',' CORE IN OUTPUT SCAN MODULE LATER')
      ELSEIF ( iwher==45 ) THEN
!
         WRITE (nout,99054)
99054    FORMAT (5X,'SORT2 REQUEST FOR STRESSES ON THE LAYERED ELEMENTS ','IS CURRENTLY NOT SET UP BY THE RIGID FORMAT')
      ELSEIF ( iwher==46 ) THEN
         WRITE (nout,99055)
99055    FORMAT (5X,'LAYER OPTION IS AVAILABLE ONLY IN STRESS OR ELSTRESS')
      ELSE
         CALL spag_block_1
         RETURN
      ENDIF
      CALL spag_block_2
      RETURN
   ENDIF
   CALL spag_block_1
CONTAINS
   SUBROUTINE spag_block_1
!
!     619 - 621 ARE DEFINED IN IFP1S
!
      WRITE (Nout,99001) Amsno
99001 FORMAT (' NO TEXT AVAILABLE FOR MESSAGE',I6)
      CALL spag_block_2
   END SUBROUTINE spag_block_1
   SUBROUTINE spag_block_2
      Line = Line + 3
      IF ( Line>=nlpp ) CALL page
   END SUBROUTINE spag_block_2
END SUBROUTINE ifp1d
