!*==/home/marcusmae/nasa/nastran/SPAGged/C_EMGTRX.f90  created by SPAG 8.01RF at 14:46 on  2 Dec 2023
MODULE C_EMGTRX
   USE ISO_FORTRAN_ENV
   REAL(REAL64), DIMENSION(225) :: A
   REAL(REAL64) :: Bfact
   REAL(REAL64), DIMENSION(18) :: E
   REAL(REAL64), DIMENSION(324) :: K, Kout
   REAL(REAL64), DIMENSION(81) :: Ksave
   REAL(REAL64), DIMENSION(9) :: Prod9, Temp9
   REAL(REAL64), DIMENSION(3) :: Xsub
END MODULE C_EMGTRX
