!*==/home/marcusmae/nasa/nastran/SPAGged/C_BLANK.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_BLANK
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(100) :: Iblnk
!
!     -------------------     / BLANK  /     ---------------------------
!
!WKBR COMMON /BLANK / IBLNK(60)
!
!WKBR DATA    IBLNK /  56*0, 4H CEA, 4HSE E, 4HMPIR, 4HE >  /
   DATA iblnk/96*0 , 4H CEA , 4HSE E , 4HMPIR , 4HE > /

END MODULE C_BLANK
