!*==/home/marcusmae/nasa/nastran/SPAGged/C_OSCENT.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_OSCENT
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   REAL, DIMENSION(200) :: Oscar
!
!     -------------------     / OSCENT /     ---------------------------
!
!     OSCENT DEFINES A STORAGE BLOCK FOR THE CURRENT OSCAR ENTRY.
!
   DATA oscar/200*4H    /
!

END MODULE C_OSCENT
