!*==/home/marcusmae/nasa/nastran/SPAGged/C_SMA1ET.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_SMA1ET
!SMA1BD
!
!
!     SMA1 VARIABLE CORE BOOKKEEPING PARAMETERS
!
!
!     SMA1 PROGRAM CONTROL PARAMETERS
!
!
!     ECPT COMMON BLOCK
!
   REAL, DIMENSION(200) :: Ecpt
END MODULE C_SMA1ET
