!*==/home/marcusmae/nasa/nastran/SPAGged/C_STIME.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_STIME
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   REAL, DIMENSION(2) :: Time
!
!     -------------------     / STIME  /     ---------------------------
!
!     STIME DEFINES USER-S ESTIMATED PROBLEM SOLUTION TIME.
!
   DATA time/2*0.0/

END MODULE C_STIME
