!*==/home/marcusmae/nasa/nastran/SPAGged/C_SYSTEM.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_SYSTEM
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(9) :: Adumel, Modcom
   INTEGER :: Apprch, Bandit, Cppgct, Ctime, Dummyi, Echof, Hicore, Iaerot, Icfiat, Icpflg, Intp, Intra, Iprec, Ithrml,  &
            & Itime, Jmax, Jrun, Ksys37, Ksys94, Ldict, Linkno, Lintc, Load, Logfl, Loglin, Lpch, Lprus, Lsystm, Maxfil,&
            & Maxopn, Mesday, Mn, Mpc, Mtemp, Mxlins, Nbpc, Nbpw, Nbrcbu, Ncpw, Nlines, Nlpp, Nogo, Nosbe, Npages,      &
            & Nprus, Ofpflg, Ospcnt, Outtap, Plotf, Pzel, Qq, Rfflag, Spc, Sperlk, Sscell, Sysbuf, Tapflg, Timew, Timez,&
            & Tlines
   LOGICAL :: Bitpas, Pass
   INTEGER, DIMENSION(3) :: Date, Hdy, K8890, Switch, Sysdat
   INTEGER, DIMENSION(56) :: Left
   INTEGER, DIMENSION(28) :: Left2
   INTEGER, DIMENSION(65) :: Ksystm
   REAL :: Tolel

   EQUIVALENCE (ksystm(1),Sysbuf)
!
!     -------------------     / SYSTEM /     ---------------------------
!
!     SYSTEM DEFINES VARIOUS MACHINE DEPENDENT, OPERATING SYSTEM AND
!     NASTRAN PARAMETERS.
!   1-
!     SYSBUF = (MACHINE DEPENDENT) NO. OF WORDS IN A GINO BUFFER.
!     OUTTAP = (MACHINE DEPENDENT) FORTRAN LOGICAL UNIT NO. FOR SYSTEM
!              PRINT OUTPUT
!     NOGO   = FLAG DEFINING EXECUTION STATUS DURING -FRONT END-.
!     INTP   = (MACHINE DEPENDENT) FORTRAN LOGICAL UNIT NO. FOR SYSTEM
!              INPUT
!     MPC    = MULTI-POINT CONSTRAINT SET ID  FOR CURRENT SUBCASE.
!     SPC    = SINGLE-POINT CONSTRAINT SET ID  FOR CURRENT SUBCASE.
!     LOGFL  = CONSOLE/LOGFILE MESSAGE CONTROL.
!     LOAD   = POINTER TO FIRST RECORD IN CASE CONTROL DATA BLOCK
!              FOR CURRENT SUBCASE.
!     NLPP   = (MACHINE DEPENDENT) NUMBER OF LINES PER PAGE OF PRINTED
!              OUTPUT.
!     MTEMP  = MATERIAL TEMPERATURE SET ID.
!  11-
!     NPAGES = CURRENT  PAGE COUNT.
!     NLINES = CURRENT NUMBER OF LINES ON CURRENT PAGE.
!     TLINES = TOTAL NUMBER OF LINES PRINTED IN JOB.
!     MXLINS = MAXIMUM NO. OF LINES OF PRINTED OUTPUT FOR THE PROBLEM.
!     DATE   = TODAY-S DATE, INTEGERS, 2 DIGITS EACH
!      (3)
!     TIMEZ  = CPU TIME IN SECONDS, WHEN PROBLEM BEGAN. NOT NECESSARY
!              ZERO. TIMEZ IS USED IN TMTOGO
!     ECHOF  = NUMBER INDICATING FORM OF BULK DATA ECHO.
!     PLOTF  = FLAG INDICATING REQUEST FOR STRUCTURAL PLOTS (NON-ZERO=
!              PLOT, SEE PLOTOPT IN SUBROUTINE NASCAR FOR MORE DETAILS)
!  21-
!     APPRCH = APPROACH FLAG (1 = FORCE, 2 = DISPL , 3 = DMAP).
!              APPRCH .LT. 0 MEANS THIS IS A RESTART.
!     LINKNO = CURRENT LINK NO. (IN BCD, E.G. NSXX)  INITIALLY SET TO
!              NS01 IN SUBROUTINE BTSTRP.  SUBSEQUENTLY SET TO THE
!              CORRECT LINK NO. IN SUBROUTINE ENDSYS.
!            = WAS THE MACHINE TYPE, MACH (LEVEL 17 AND EALIDER VERSION)
!     LSYSTM = LENGTH OF SYSTEM COMMON BLOCK.
!     ICFIAT = REPLACING EDTUMF FLAG HERE, WHICH IS NO LONGER USED.
!    (EDTUMF)  ICFIAT IS THE NUMBER OF WORDS PER FIAT ENTRY.
!            . IF ICFIAT=8, DATA BLOCK GINO TRAILER 6 WORDS ARE PACKED
!              INTO 4TH, 5TH, AND 6TH WORDS OF EACH FIAT ENTRY.
!            . IF ICFIAT=11, NO PACKING IN FIAT ENTRY, AND THE TRAILER 6
!              WORDS ARE SAVED IN 4TH THRU 6TH, AND 9TH THRU 11TH WORDS.
!              THE TRAILER WORDS ARE THEREFORE NOT BOUNDED BY SIZE
!              LIMITATION OF 65535 (HALF OF A 32-BIT WORD).
!            . THE FIAT POINTERS IN /XFIST/ MUST BE IN COMPLETE AGREE-
!              MENT WITH THE SELECTION OF ICFIAT=8, OR ICFIAT=11.
!              (SEE THE DATA SETTING OF /XFIST/ BELOW)
!            . THE REST OF NASTRAN .MIS ROUTINES ARE CODED TO HANDLE
!              ICFIAT=8 OR 11 AUTOMATICALLY. THE .MDS ROUTINES ARE NOT
!              AFFECTED SINCE THE 7TH AND 8TH WORDS OF THE FIAT ENTRY
!              REMAIN UNCHANGED.
!            = WAS EDTUMF FLAG, USED IN PRE-1987 NASTRAN VERSION
!     RFFLAG = RIGID FORMAT FLAG
!     CPPGCT = PAGE COUNT USED BY XCHK ROUTINE
!     MN     = NUMBER OF RINGS/NUMBER OF HARMONICS FOR AXISYMMETRIC
!              SHELL.
!     DUMMYI = (UNUSED WORD)
!     MAXFIL = MAXIMUM NUMBER OF UNITS TO BE ALLOCATED TO FIAT.
!     MAXOPN = MAXIMUM NUMBER OF FILES OPEN AT ONE TIME.
!  31-
!     HICORE = HI-CORE LENGTH FOR UNIVAC AND VAX
!     TIMEW  = PROBLEM START TIME (INTEGR SECONDS AFTER MIDNITE)
!     OFPFLG = OFP OPERATE FLAG - SET NON-ZERO WHEN OFP OPERATES
!     NBRCBU = (CDC ONLY) LENGTH OF FET + DUMMY INDEX
!              UNIVAC DRUM FILE ALLOCATION (1 FOR POSITION, 2 FOR TRACK)
!     LPRUS  = (CDC ONLY) NUMBER OF WORDS PER PHYSICAL RECORD UNIT (PRU)
!     NPRUS  = (CDC ONLY) NUMBER OF PRU-S PER GINO RECORD BLOCK
!     KSYS37 = ERROR CONTROL WORD, USED LOCALLY BY QPARMD AND QPARMR.
!              ALSO USED LOCALLY IN LINK1 FOR NASINFO FILE UNIT NO.
!     QQ     = HYDROELASTIC PROBLEM FLAG.
!     NBPC   = (MACHINE DEPENDENT) NO. OF BITS PER CHARACTER.
!     NBPW   = (MACHINE DEPENDENT) NO. OF BITS PER WORD.
!  41-
!     NCPW   = (MACHINE DEPENDENT) NO. OF CHARACTERS PER WORDS.
!     SYSDAT = THREE BCD WORD ARRAY CONTAINING MONTH, ' 19', AND LAST
!      (3)     TWO DIGITS OF YEAR OF SYSTEM GENERATION DATE.
!              THESE CELLS ARE SET BY SUBROUTINE NASCAR.
!     TAPFLG = WORD SET BY NASTRAN CARD TO INDICATE FILES TO BE TAPES
!              WHETHER OR NOT THEY ARE ON DISK.  BITS TURNED ON COUNTING
!              FROM RIGHT REPRESENT THE FILES IN XXFIAT.
!     ADUMEL = NINE WORD ARRAY CONTAINING DATA EXTRACTED FROM THE ADUM-I
!      (9)     CARDS BY IFP.
!  55-
!     IPREC  = PRECISION FLAG, 1=SP, 2=DP.
!     ITHRML = THERMAL ANALYSIS FLAG,  0=STRUCTURAL ANALYSIS,
!                                      1=THERMAL ANALYSIS.
!     MODCOM = NINE WORD ARRAY FOR MODULE COMMUNICATIONS.
!      (9)     SYSTEM(58), PRE-SELECT METHOD FOR MPYAD (1,2,3,DEFAULT=0)
!              SYSTEM(59), PLOT TAPE TRACK SIZE
!  66-
!     HDY    = THREE WORD ARRAY ALA SEW
!      (3)
!     SSCELL = MULTILEVEL SUBSTRUCTURE ANALYSIS COMMUNICATION CELL.
!     TOLEL  = SINGULARITY TOLERANCE FOR SMA1,EMG. RESET BY NASCAR.
!  71-
!     MESDAY = DAYFILE MESSAGE FLAG
!     BITPAS = CDC TAPE PROCESSING BIT - FALSE FOR LINK1 ONLY
!     PASS   = CDC MESSAGE AND TIMING FLAG - FALSE FOR LINK1 ONLY
!     ITIME  = WAS: WALL TIME ELAPSED SINCE PROBLEM START (SECONDS)
!            = IS : PROBLEM START TIME IN SECONDS SINCE JAN-1-1970,
!                   GREENWICH-MEAN-TIME (GMT)
!     CTIME  = WAS: CENTRAL PROCESSOR TIME SINCE PROBLEM START (SECONDS)
!            = IS : PRINT FLAG FOR DMAP SEQUENCE NO. AND NAME, ALL LINKS
!                   (SEE NASTRN OR NAST01.MDS)
!     NOSBE  = (CDC ONLY) FLAG FOR NOS(0) OR NOSBE(1)
!     BANDIT = BANDIT OPTION FLAG (SEE BANDIT FOR MORE DETAILS)
!     PZEL   = PIEZOELECTRIC PROBLEM FLAG (INPUT VIA NASTRAN SYSTEM(78))
!     SWITCH = SENSE SWITCH BITS FOR DIAG CARD AND USED BY SSWTCH
!      (3)
!  82-
!     ICPFLG = CHECKPOINT FLAG (0 = NO CHECKPOINT, 1 = CHECKPOINT)
!     JRUN   = JRUN FOR VARIAN  (HEAT PROBLEM)
!     JMAX   = JMAX FOR VARIAN  (HEAT PROBLEM)
!     LINTC  = MAX. ALLOWABLE LINES OF INTERSECTION USED IN HDPLOT
!     INTRA  = INTERACTIVE REQUEST FLAG FOR PLOT, OUTPUT, AND SCAN
!              (0=NONE, 1=PLOT ONLY, 2=OUTPUT PRINT AND SCAN ONLY,
!               3=BOTH)
!     OSPCNT = BAR OFFSET WARNING MESSAGE IF OFFSET BAR LENGTH EXCEEDS
!              NON-OFFEST LENGTH BY THIS LIMIT (DEFAULT IS 15 PERCENT)
!     K88 90 = 3 WORDS RESERVED FOR USER. WILL NOT BE USED BY COSMIC
!              =========================
!  91-
!     LPCH   = (MACHINE DEPENDENT) FORTRAN LOGICAL UNIT NO. FOR PUNCH
!     LDICT  = FORTRAN LOGICAL UNIT NO. FOR RESTART DICTIONARY PUNCH
!     IAEROT = INTEGER FLAG INDICATING AERODYNAMIC THEORY
!              (SPECIFIED VIA NASTRAN CARD AND USED ONLY IN APDB MODULE
!              0 FOR COMPRESSOR BLADES, THEORY 6, DEFAULT,
!              1 FOR SWEPT TURBOPROP. BLADES, THEORY 7)
!     KSYS94 = FLAG FOR REMOVALS OF MPYDRI(1), MPY4T(10), NEW FBS(100),
!              TRNSPS(1000), AND NEW FBS IN FEER(10000)
!     SPERLK = NASTRAN SUPERLINK FLAG. SET BY SEMDBD OR NASTRN
!              FOR UNIX MACHINE
!     LEFT   = (85 UNUSED WORDS).  KSYS99 USED IN ERRTRC
!
!                   USED ONLY IN MSFC, UNIVAC VERSION - LOGFL = 190
!        VAX: HICORE IS SET TO 50,000 BY BTSTRP
   DATA sysbuf , outtap , nogo , intp , mpc , spc , logfl/0 , 0 , 0 , 0 , 0 , 0 , 0/ , load , nlpp , mtemp , npages , nlines ,      &
      & tlines , mxlins/1 , 0 , 0 , 0 , 0 , 0 , 20000/ , date , timez , echof , plotf , apprch , linkno , lsystm/3*0 , 0 , 2 , 0 ,  &
      & 0 , 0 , 180/ , icfiat , rfflag , cppgct , mn , dummyi , maxfil , maxopn/11 , 0 , 0 , 0 , 0 , 35 , 16/ , hicore , timew ,    &
      & ofpflg , nbrcbu , lprus , nprus , ksys37/85000 , 0 , 0 , 15 , 64 , 0 , 0/ , qq , nbpc , nbpw , ncpw , sysdat , tapflg ,     &
      & adumel/0 , 0 , 0 , 0 , 3*0 , 0 , 9*0/ , iprec , ithrml , modcom , hdy , sscell , tolel , mesday/0 , 0 , 9*0 , 3*0 , 0 ,     &
      & 0.01 , 0/
   DATA bitpas , pass , itime , ctime , nosbe , bandit , pzel/2*.FALSE. , 0 , 0 , 0 , 0 , 0/ , switch , icpflg , jrun , jmax ,      &
      & lintc , intra , ospcnt/3*0 , 0 , 0 , 0 , 800 , 0 , 15/ , k8890 , lpch , ldict , iaerot , ksys94 , sperlk , left , loglin ,  &
      & left2/3*0 , 0 , 0 , 0 , 0 , 0 , 56*0 , 0 , 28*0/

END MODULE C_SYSTEM
