!*==/home/marcusmae/nasa/nastran/SPAGged/C_XCEITB.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XCEITB
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(42) :: Cei
!
!     -------------------     / XCEITB /     ---------------------------
!
!     XCEITB DEFINES LOOP CONTROL PARAMETERS FOR THE CONTROL ENTRY
!     INTERP.
!     CEI(1) = TOTAL NO. OF WORDS IN TABLE.
!     CEI(2) = POINTER TO LAST WORD USED.
!     CEI(3) = TABLE OF FOUR-WORD ENTRIES.
!
   DATA cei/42 , 2 , 40*0/
!

END MODULE C_XCEITB
