!*==/home/marcusmae/nasa/nastran/SPAGged/C_XDPL.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XDPL
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(240) :: Dpl
   INTEGER :: Ldpl, Mdpl, Ndpl
!
!     -------------------     / XDPL   /     ---------------------------
!
!     XDPL DEFINES THE DATA POOL DICTIONARY.
!     MDPL   = POINTER TO NEXT AVAILABLE FILE.
!     NDPL   = TOTAL NO. OF ENTRIES IN DPL.
!     LDPL   = CURRENT NO. OF ENTRIES IN DPL.
!     DPL    = TABLE OF THREE-WORD ENTRIES
!              1ST + 2ND WORDS ARE DATA BLOCK NAME
!              3RD WORD DEFINES EQUIV FLAG, APPROX SIZE OF DATA BLOCK
!              AND FILE NO. IN THE POOL.
!
   DATA mdpl/1/ , ndpl/80/ , ldpl/0/ , dpl/240*0/

END MODULE C_XDPL
