!*==/home/marcusmae/nasa/nastran/SPAGged/C_XLINK.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XLINK
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER :: Lxlink, Maxlnk
   INTEGER, DIMENSION(220) :: Mxlink
!
!     -------------------     / XLINK  /     ---------------------------
!
!     SPECIFIES MODULE LINK RESIDENCE, AND PROVIDES LINK SWITCHING
!     INFORMATION FOR LINK DRIVER SUBROUTINES, XSEMi.
!     LXLINK = NUMBER OF WORDS IN MXLINK.
!     MAXLNK = MAX NUMBER OF LINKS - SEE XGPIBS IF THIS NUMBER IS
!              INCREASED.
!     MXLINK = MODULE LINK SPECIFICATION TABLE - THIS TABLE IS
!              INITIALIZED BY SUBROUTINE XGPIBS.
!
   DATA lxlink/220/ , maxlnk/15/ , mxlink/220*0/

END MODULE C_XLINK
