!*==/home/marcusmae/nasa/nastran/SPAGged/C_XMDMSK.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XMDMSK
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER, DIMENSION(7) :: Msk
   INTEGER :: Nmskcd, Nmskfl, Nmskrf
!
!     -------------------     / XMDMSK /     ---------------------------
!
!     XMDMSK DEFINES MASK FOR MODIFIED RESTART.
!     NMSKCD = NUMBER OF MASK WORDS FOR CARDS (CURRENTLY SET TO 3)
!     NMSKFL = NUMBER OF MASK WORDS FOR FILES (CURRENTLY SET TO 3)
!     NMSKRF = NUMBER OF MASK WORDS FOR RIGID FORMATS (CURRENTLY 1)
!     MSK    = MASK OF (NMSKCD+NMSKFL+NMSKRF) WORDS (31 BITS/WORD)
!
   DATA nmskcd , nmskfl , nmskrf , msk/3 , 3 , 1 , 7*0/

END MODULE C_XMDMSK
