!*==/home/marcusmae/nasa/nastran/SPAGged/C_XPFIST.f90  created by SPAG 7.61RG at 01:00 on 21 Mar 2022
MODULE C_XPFIST
!
!     *****  PRINCIPAL BLOCK DATA PROGRAM FOR NASTRAN  *****
!     (NOTE - MACHINE DEPENDENT CONSTANTS ARE INITIALIZED IN BTSTRP)
!
!     REVISED 7/91 BY G.CHAN/UNISYS
!     MAKE SURE THERE IS NO VARIABLES OR ARRAYS NOT INITIALIZED. GAPS
!     OR MISSING INITIALIZED DATA MAY CAUSE PROBLEMS IN SOME MACHINES.
!
   INTEGER :: Npfist
!
!     -------------------     / XPFIST /     ---------------------------
!
!     XPFIST DEFINES THE NO. OF PERMANENT ENTRIES IN THE FIST.
!
   DATA npfist/24/

END MODULE C_XPFIST
