
SUBROUTINE cmckdf
   IMPLICIT NONE
   REAL Buf1 , Buf3 , Buf4 , Buf5 , Casecc , Conect , Conset , Geom4 , Origin(7,3) , Restct(7,7) , Scbdat , Scmcon , Scr1 , Scr2 ,  &
      & Scr3 , Sctoc , Step , Toler , Tran , Z(1)
   INTEGER Buf2 , Combo(7,5) , Iauto , Idry , Intp , Iprint , Isort , Iz(1) , Lcore , Mcon , Npsub , Outt , Scconn , Sccstm ,       &
         & Score , Scsfil
   CHARACTER*23 Ufm
   COMMON /blank / Step , Idry
   COMMON /cmb001/ Scr1 , Scr2 , Scbdat , Scsfil , Scconn , Scmcon , Sctoc , Geom4 , Casecc , Sccstm , Scr3
   COMMON /cmb002/ Buf1 , Buf2 , Buf3 , Buf4 , Buf5 , Score , Lcore , Intp , Outt
   COMMON /cmb003/ Combo , Conset , Iauto , Toler , Npsub , Conect , Tran , Mcon , Restct , Isort , Origin , Iprint
   COMMON /xmssg / Ufm
   COMMON /zzzzzz/ Z
   INTEGER ce(9) , cstmid(7) , ecpt1 , i , ibgss , icstm , idpsub(7) , ifile , imsg , ist(7) , isub , isum , j , jj , k , kk ,      &
         & llco , loc , nam(2) , ncsub , nn , npt , nptm1 , nw
   REAL cstm(7,9) , ecpt(4) , tt(9)
   LOGICAL ferror , first
!
!     THIS SUBROUTINE DETERMINES WHETHER ALL (TRANSFORMED) LOCAL
!     COORDINATE SYSTEMS SPECIFIED AT A GIVEN CONNECTION ARE COMPATABLE
!
   EQUIVALENCE (Iz(1),Z(1)) , (ecpt1,ecpt(1))
   DATA nam/4HCMCK , 4HDF  /
!
   DO i = 2 , 4
      ecpt(i) = 0.0
   ENDDO
   ferror = .TRUE.
!
!     READ CSTM INTO OPEN CORE
!
   ifile = Sccstm
   icstm = Score
   llco = Lcore
   CALL open(*400,Sccstm,Z(Buf2),0)
   CALL read(*100,*100,Sccstm,Z(icstm),llco,1,nw)
   GOTO 600
 100  llco = llco - nw
   CALL close(Sccstm,1)
   IF ( nw==0 ) GOTO 99999
   CALL pretrs(Z(icstm),nw)
!
!     READ ALL BGSS FILES INTO OPEN CORE
!
   ibgss = Score + nw
   ifile = Scsfil
   CALL open(*400,Scsfil,Z(Buf2),0)
   jj = 0
   DO i = 1 , Npsub
      ist(i) = ibgss + jj
      ncsub = Combo(i,5) + 1
      DO j = 1 , ncsub
         CALL fwdrec(*500,Scsfil)
      ENDDO
      CALL read(*400,*150,Scsfil,Z(ibgss+jj),llco,1,nn)
      GOTO 600
 150  llco = llco - nn
      jj = jj + nn + 1
      CALL skpfil(Scsfil,1)
   ENDDO
   CALL close(Scsfil,1)
!
!     BEGIN READING CONNECTION ENTRIES
!
   ifile = Scconn
   CALL open(*400,Scconn,Z(Buf2),0)
   CALL read(*300,*200,Scconn,ce,10,1,nn)
   GOTO 600
 200  npt = 0
   DO i = 1 , Npsub
!
!     CE(3)...CE(NN) ARE INTERNAL POINT NO.
!
      IF ( ce(i+2)/=0 ) THEN
         npt = npt + 1
         loc = ist(i) + (ce(i+2)-1)*4
         cstmid(npt) = Iz(loc)
         idpsub(npt) = i
      ENDIF
   ENDDO
!
!     CHECK FOR NO CSTMS THIS ENTRY
!
   isum = 0
   DO i = 1 , npt
      isum = isum + cstmid(i)
   ENDDO
   IF ( isum/=0 ) THEN
!
!     GET CSTM MATRICES AND LOAD INTO CSTM ARRAY
!
      DO i = 1 , npt
         ecpt1 = cstmid(i)
         IF ( ecpt1==0 ) THEN
            DO j = 1 , 9
               cstm(i,j) = 0.0
            ENDDO
            cstm(i,1) = 1.0
            cstm(i,5) = 1.0
            cstm(i,9) = 1.0
         ELSE
            CALL transs(ecpt,tt)
            DO j = 1 , 9
               cstm(i,j) = tt(j)
            ENDDO
         ENDIF
      ENDDO
!
!     COMPARE EACH MATRIX AGAINST OTHERS
!
      nptm1 = npt - 1
      DO i = 1 , nptm1
         first = .TRUE.
         j = i + 1
         DO k = j , npt
            DO kk = 1 , 9
               IF ( abs(cstm(i,kk)-cstm(k,kk))>=1.E-3 ) GOTO 210
            ENDDO
            CYCLE
 210        IF ( ferror ) THEN
               ferror = .FALSE.
               WRITE (Outt,99001) Ufm
!    2        ', SUMMARY FOLLOWS.', /5X,'(LOCAL COORDINATE SYSTEMS ARE',
!    3        ' THE TRNASFORMED OVERALL STSTEM GENERATED BY COMB1,',
!    4        /5X,'SEE PROGRM. MANUAL P 4.128-7, 9TH STEP)', //,
!    5        ' *** SUGGESTION - YOUR SUBSTRUCTURING PROBLEM MAY ',
!    6        'REQUIRE THE ''GTRAN'' CARD(S) ***',/)
!
99001          FORMAT (A23,' 6528, INCOMPATABLE LOCAL COORDINATE SYSTEMS HAVE ','BEEN FOUND.',/5X,                                  &
                      &'CONNECTION OF POINTS IS IMPOSSIBLE','. (SUGGESTION - USE ''GTRAN'' CARD(S))',/5X,                           &
                      &'SUMMARY IN TERMS OF THE JUST-FORMED INTERNAL DOF AND ','INTERNAL COORD. SYSTEM ID''S PER',/5X,              &
                      &'THE EQSS AND BGSS FOLLOWS.',/)
            ENDIF
            IF ( first ) THEN
               first = .FALSE.
               isub = idpsub(i) + 2
               WRITE (Outt,99002) cstmid(i) , cstm(i,1) , cstm(i,4) , cstm(i,7) , idpsub(i) , cstm(i,2) , cstm(i,5) , cstm(i,8) ,   &
                                & ce(isub) , cstm(i,3) , cstm(i,6) , cstm(i,9)
99002          FORMAT (/1X,76(1H*),/,' THE FOLLOWING MISMATCHED LOCAL COORDINATE',' SYSTEMS (CSTM) HAVE BEEN FOUND FOR',//,         &
                      &' LOCAL COORDINATE SYSTEM ID NO.',I9,8X,3E9.2,/,' PSEUDOSTRUCTURE ID NO.',I5,20X,3E9.2,/,                    &
                      &' INTERNAL POINT NO.',I9,20X,3E9.2)
               Idry = -2
            ENDIF
            isub = idpsub(k) + 2
            WRITE (Outt,99003) cstmid(k) , cstm(k,1) , cstm(k,4) , cstm(k,7) , idpsub(k) , cstm(k,2) , cstm(k,5) , cstm(k,8) ,      &
                             & ce(isub) , cstm(k,3) , cstm(k,6) , cstm(k,9)
99003       FORMAT (/12X,'AND',7X,'LOCAL COORDINATE SYSTEM ID NO.',I9,8X,3E9.2,/22X,'PSEUDOSTRUCTURE ID NO.',I5,20X,3E9.2,/22X,     &
                   &'INTERNAL POINT NO.',I9,20X,3E9.2)
         ENDDO
      ENDDO
   ENDIF
   CALL read(*300,*200,Scconn,ce,10,1,nn)
   GOTO 600
!
 300  CALL close(Scconn,1)
   GOTO 99999
!
 400  imsg = -1
   GOTO 700
 500  imsg = -2
   GOTO 700
 600  imsg = -8
 700  CALL mesage(imsg,ifile,nam)
!
99999 RETURN
END SUBROUTINE cmckdf
