
SUBROUTINE errmkn(N,Ierr)
   IMPLICIT NONE
!
! COMMON variable declarations
!
   INTEGER Nbuff , Nout
   CHARACTER*25 Sfm , Uwm
   CHARACTER*23 Ufm
   CHARACTER*29 Uim
   COMMON /system/ Nbuff , Nout
   COMMON /xmssg / Ufm , Uwm , Uim , Sfm
!
! Dummy argument declarations
!
   INTEGER Ierr , N
!
! Local variable declarations
!
   INTEGER isubr(26)
!
! End of declarations
!
!
!     SENDS ERROR MESSAGES.  N IS THE INDEX OF THE SUBROUTINE CALLING
!     ERROR, AND IERR IS AN ERROR CODE.
!
   DATA isubr/4HCRSU , 4HB    , 4HDSTR , 4HOY   , 4HFDIT , 4H     , 4HFMDI , 4H     , 4HFNXT , 4H     , 4HGETB , 4HLK   , 4HRETB ,  &
       &4HLK   , 4HSETE , 4HQ    , 4HSJUM , 4HP    , 4HSURE , 4HAD   , 4HRENA , 4HME   , 4HEXO2 , 4H     , 4HEXIO , 4H1   /
!
   WRITE (Nout,99001) Sfm , isubr(N) , isubr(N+1)
!
99001 FORMAT (A25,' 6224, SOF UTILITY SUBROUTINE ',2A4)
   CALL sofcls
   IF ( Ierr==2 ) THEN
      WRITE (Nout,99002)
99002 FORMAT (5X,'ILLEGAL BLOCK NUMBER')
   ELSEIF ( Ierr==3 ) THEN
      WRITE (Nout,99003)
99003 FORMAT (5X,'ERROR IN SETTING UP THE LIST IMORE')
   ELSEIF ( Ierr==4 ) THEN
      WRITE (Nout,99004)
99004 FORMAT (5X,'NXTCUR IS TOO LARGE')
   ELSEIF ( Ierr==5 ) THEN
      WRITE (Nout,99005)
99005 FORMAT (5X,'ERROR IN UPDATING DIT')
   ELSEIF ( Ierr==6 ) THEN
      WRITE (Nout,99006)
99006 FORMAT (5X,'ERROR IN UPDATING MDI')
   ELSEIF ( Ierr==7 ) THEN
      WRITE (Nout,99007)
99007 FORMAT (5X,'ERROR IN LINKING BLOCKS OF DIT')
   ELSEIF ( Ierr==8 ) THEN
      WRITE (Nout,99008)
99008 FORMAT (5X,'LINK THROUGH COMBINED SUBSTRUCTURES IS NOT CIRCULAR')
   ELSEIF ( Ierr==9 ) THEN
      WRITE (Nout,99009)
99009 FORMAT (5X,'ERROR IN LINKING SOF BLOCKS')
   ELSEIF ( Ierr==10 ) THEN
      WRITE (Nout,99010)
99010 FORMAT (5X,'INTERNAL ARRAY DIMENSION EXCEEDED')
   ELSE
      WRITE (Nout,99011)
99011 FORMAT (5X,'I IS TOO LARGE OR NXTTSZ HAS NOT BEEN PROPERLY ','UPDATED')
   ENDIF
   CALL mesage(-61,0,0)
   RETURN
END SUBROUTINE errmkn
