
SUBROUTINE olplot
   IMPLICIT NONE
!
! COMMON variable declarations
!
   INTEGER Ibuf , Nout
   COMMON /system/ Ibuf , Nout
!
! Local variable declarations
!
   INTEGER plt2
!
! End of declarations
!
!
!     DRIVER FOR USER SUPPLIED INTERACTIVE PLOTTER
!
!     NOTE - ALL FORTRAN STOPS MUST BE CHANGED TO RETURNS
!     OTHERWISE THE FORTRAN STOPS WILL KILL THE INTERACTIVE SESSION.
!
   DATA plt2/13/
!
   WRITE (Nout,99001)
99001 FORMAT ('    USER MUST SUPPLY SITE DEPENDENT PLOTTING PACKAGE',/4X,'IN SUBROUTINE OLPLOT FOR INTERACTIVE PLOTS')
!
!
   REWIND plt2
!     CALL THE SITE DEPENDENT PLOTTING ROUTINES HERE.
!     CALL NASPLOT
END SUBROUTINE olplot
